services:
  hydra-db:
    image: postgres:16-alpine
    container_name: hydra-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: hydra
      POSTGRES_PASSWORD: hydra123
      POSTGRES_DB: hydra_iam
    volumes:
      - hydra_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - hydra-network

  hydra-core:
    image: node:24-alpine
    container_name: hydra-api-dev
    working_dir: /app
    command: sh -c "npm install && npm run start:dev"
    volumes:
      - ./apps/hydra-core:/app
      - /app/node_modules
    # Cambiamos a formato de mapeo (sin guiones) para evitar errores de tipo
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      CHOKIDAR_INTERVAL: "500" 
      NODE_ENV: development
    stdin_open: true
    tty: true
    env_file:
      - ./apps/hydra-core/.env.docker
    ports:
      - "3000:3000"
    depends_on:
      - hydra-db
    networks:
      - hydra-network


networks:
  hydra-network:
    driver: bridge

volumes:
  hydra_db_data:
