services:
  hydra-db:
    image: postgres:16-alpine
    container_name: hydra-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - hydra_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - hydra-network

  hydra-api:
    image: hydra-iam-backend
    container_name: hydra-api
    restart: unless-stopped
    depends_on:
      - hydra-db
    env_file:
      - .env.docker
    ports:
      - "3000:3000"
    networks:
      - hydra-network

networks:
  hydra-network:
    driver: bridge

volumes:
  hydra_db_data:
